### ISSUE TITLE
No function clause matching in Trot.LiveReload.check_reload/2

### ISSUE THREAD

**Issue by mmichaa** [hexedpackets/trot_example#1]
Hi,

the example does not work for me. But I'm an elixir noob, maybe I missed something.

1. clone repository
2. run `mix deps.get`
3. run `mix trot.server`
4. run `curl http://localhost:4000/text`

expected result _(on curl)_:
```
"Thank you for your question."
```

actual result _(on server)_:
```
17:17:03.610 [error] #PID<0.878.0> running TrotExample.Router terminated
Server: localhost:4000 (http)
Request: GET /text
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Trot.LiveReload.check_reload/2
        (trot) lib/trot/live_reload.ex:33: Trot.LiveReload.check_reload({:noop, []}, %Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "localhost", method: "GET", owner: #PID<0.878.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["text"], path_params: %{}, peer: {{127, 0, 0, 1}, 56678}, port: 4000, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"host", "localhost:4000"}, {"user-agent", "curl/7.54.0"}, {"accept", "*/*"}], request_path: "/text", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil})
        (trot_example) lib/trot_example/router.ex:1: TrotExample.Router.plug_builder_call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /private/tmp/trot_example/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

notes:
It works when I set the default pre_routing list without `"Elixir.Trot.LiveReload"`.

env:
```
$ uname -a
Darwin michaBookPro.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

$ elixir --version
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

$ mix deps
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:10

* ranch 1.3.2 (Hex package) (rebar3)
  locked at 1.3.2 (ranch) e4965a14
  ok
* poison 3.1.0 (Hex package) (mix)
  locked at 3.1.0 (poison) d9eb6366
  ok
* cowlib 1.0.2 (Hex package) (rebar3)
  locked at 1.0.2 (cowlib) 9d769a1d
  ok
* cowboy 1.1.2 (Hex package) (rebar3)
  locked at 1.1.2 (cowboy) 61ac29ea
  ok
* mime 1.2.0 (Hex package) (mix)
  locked at 1.2.0 (mime) 78adaa84
  ok
* calliope 0.4.2 (Hex package) (mix)
  locked at 0.4.2 (calliope) 29d85853
  ok
* plug 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (plug) 236d77ce
  ok
* plug_heartbeat 0.2.0 (Hex package) (mix)
  locked at 0.2.0 (plug_heartbeat) 912485e2
  ok
* trot 0.6.0 (https://github.com/hexedpackets/trot.git) (mix)
  locked at 1e18c83
  ok

```

**Comment by hexedpackets** [comment]
This was due to the response of the compile mix task changing between Elixir 1.5 and 1.6. I fixed the plug upstream in Trot and updated the mix.lock in this repo, so it should be good to go now.
